---
title: "Teoría de Decisión: Trabajo Modelo Markowitz"
author:
-  Juan Carlos Martínez-Ovando
-  jc-mo@tec.mx
date: "Feb-Jun 2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: yes
    self_contained: yes
    theme: cerulean
    highlight: textmate
fig_align: "center"
fig_width: 18
---

# Actividades

Consideren tres datos/series entre las cinco opciones incluidas en el script `cd2007_3_dataseries.R`, descargados con `quantmod` o alguna otra herramienta, tomando en cuenta:

* Freciencia `diaria`

* Columna de `precios ajustados` (`adjusted prices`) de las tres series

* Fechas en las que las tres series tienen registros.

Con base en lo anterior:

a. Calcula los estimadores del `vector de medias` y de la `matriz de varianzas y covarianzas` de los retornos logaritmicos.

b. Desxribe una implementacion computacional  empleada para obtener la estrategia optima de inversion de Markowitz, con base en los estimadores puntuales del inciso (a).

c. Reporta la estrategia optima de inversion, de acuerdo al enfoque de Markowitz, que fue implementado en el inciso (b).

d. Interpreta los resultados obtenidos de la estrategia de inversion optima, complementando con la informacion generada a partir de los estimadores puntuales calculados en el inciso (a).

# Equipo de Trabajo

*Completa el número y nombre completo (con clave de estudiantes) de los integrantes del equipo.*

**Equipo <Sust.Núm.>**

* <Integrante 1>

* <Integrante 2>

* ...

# Soluciones

*Desarrollen en esta sección la solución, estructurando las partes por subsecciones*

## Sub-seccion 1

### Sub-subseccion 1

## Sub-seccion 2

## ...

# Forma de entrega

* Nombren los archivos de sus soluciones como 
`Equipo_<>_Trabajo_Decision_01`.

* Cada miembro del equipo debe entregar los documentos de su equipo de trabajo de la seccion `Student work` correspondiente en `Google Classroom` (i.e. el mismo documento por cada miembro del equipo).

* Cada estudiante, por separado, debe incluir una reflexión del trabajo realizado junto con la descripción de su participación en la solución. Esto dentro de la sección de comentarios del `Student work` correspondiente.
