---
title: "Teoría de Decisión: Trabajo Distribución Gaussiana"
author:
-  Juan Carlos Martínez-Ovando
-  jc-mo@tec.mx
date: "Feb-Jun 2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: yes
    self_contained: yes
    theme: cerulean
    highlight: textmate
fig_align: "center"
fig_width: 18
---

# Actividades

Deescarguen los siguientes datos de `quantmod`:

* *US Treasury Bond Index* (t10yr) del sitio de la `FED EEUU`

* *S&P500 Index* del sitio `Yahoo! Finance`

Los datos deben `diarios` correspondientes al periodo `01-ene-1990` a `31-dec-2016`.

Con base en lo anterior:

a. Calcula los retornos diarios de ambos productos financieros.

b. Calcula el vector de medias, matriz de varianzas y covarianzas, y matriz de precisión de la `distribucion baussiana bivariada` para los retornos conjuntos de ambos activos financieros.

c. Calcula la probabilidad de que el retorno diario del *US Treasury Bond Index* sea mayor al 8 por ciento.

d. Calcula la probabilidad de que el retorno diario del *S&P 500 Index* sea menor al -3 porciento o mayor al 3.5 por ciento.

e. Si definimos un portafolio compuesto por los pesos:
$$
\boldsymbol{w}= (w_1,w_2)=(0.65,0.35),
$$
determina la distribución de probabilidades del retorno del portafolio.

f. Calcula la probabilidad de que el retorno diario del portafolio (e) sea mayor a 4.75 por ciento.


# Equipo de Trabajo

*Completa el número y nombre completo (con clave de estudiantes) de los integrantes del equipo.*

**Equipo <Sust.Núm.>**

* <Integrante 1>

* <Integrante 2>

* ...

# Soluciones

*Desarrollen en esta sección la solución, estructurando las partes por subsecciones*

## Sub-seccion 1

### Sub-subseccion 1

## Sub-seccion 2

## ...

# Forma de entrega

* Nombren los archivos `RMD` y `HTML` de sus soluciones como 
`Equipo_<>_Trabajo_Decision_01`.

* Cada miembro del equipo debe entregar los documentos `RMD` y `HTML` de su equipo de trabajo en el `Student work` correspondiente de `Google Classroom` (el mismo documento).

* Cada estudiante, por separado, debe incluir una reflexión del trabajo realizado junto con la descripción de su participación en la solución. Esto dentro de la sección de comentarios del `Student work` correspondiente.
