---
title: "CD2007 Semana 03 Case3Sol"
author: "Juan Carlos Martinez Ovando"
date: "26/2/2020"
output: pdf_document
#output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Case 3: Production of two models of chairs  {.tabset .tabset-fade .tabset-pills}

A company produces two models of chairs: 4P and 3P. The model 4P needs 4 legs, 1 seat and 1 back. On the other hand, the model 3P needs 3 legs and 1 seat. The company has a initial stock of 200 legs, 500 seats and 100 backs. If the company needs more legs, seats and backs, it can buy standard wood blocks, whose cost is 80 e per block. The company can produce 10 seats, 20 legs and 2 backs from a standard wood block.

The cost of producing the model 4P is 30 e/chair, meanwhile the cost of the model 3P is 40 e/chair. Finally, the company informs that the minimum number of chairs to produce is 1,000 units per month.

## Objectives

> 1. Define a linear programming model, which minimizes the total cost (the production costs of the two chairs, plus the buying of new wood blocks).

Due to the economic crisis, the company has considered the possibility to just produce a single chair model between 3P and 4P.

> 2. Define the new linear programming model for producing only a single chair model, which minimizes the total cost.

Finally, the new CEO (Chief Executive Officer) of the company has decided that the factory needs to produce of the model 4P a minimum of 4 times the quantity of the model 3P.

> 3. Define the new linear programming model, which minimizes the total cost when producing 4P four times the quantity of 3P.

# Solution

