---
title: "Week 01 - Linear programme – Part 1/4 "
author:
-  Juan Carlos Martínez-Ovando
-  jc-mo@tec.mx
date: "Feb-Jun 2020"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: yes
    self_contained: yes
    theme: cerulean
    highlight: textmate
fig_align: "center"
fig_width: 18
---

# Objetives  {.tabset .tabset-fade .tabset-pills}

* Conceptually describe in what situations the linear programming method can be applied, and what this quantitative tool consists of.

* Describe the general steps to follow in solving linear programming problems.

* Determine the practical elements necessary to implement a solution with the linear programming method.

---

# Motivating case study

**A resource allocation problem**

A company produces copper cable of 5 and 10 mm of diameter on a
single production line with the following constraints:

a.  The available copper allows to produces 21000 meters of cable of
5 mm diameter per week.

b. A meter of 10 mm diameter copper consumes 4 times more copper than a meter of 5 mm diameter copper.

Due to demand, the weekly production of 5 mm cable is limited to
$15,000$ meters and the production of 10 mm cable should not exceed
40 percent of the total production. Cable are respectively sold 50 and 200 EUR the meter.

> Question: **What should the company produce in order to maximize its weekly revenue?**

## Some other examples

> Let us take a few minutes to formulate similar to the `motivating case study` based in our everyday life.

---

# Introduction to **optimization**

## Montivation

Why **linear programming** is a very important topic?

* A lot of problems can be formulated as linear programmes.

* Nowadays, here exist efficient methods to solve them -- or at least give good approximations--.

## What is a **linear programm**?

It is an *optimization problem* consisting in

a. maximizing (or minimizing) a `linear objective` function of $n$ decision variables

b. subject to a set of constraints expressed by linear equations or
inequalities.

## History

It was originated within a military context: 

> `programme` = `resource planning`

The terminology is due to *George B. Dantzig*, inventor of the Simplex
Algorithm (1947), developed during WWII and published right afterwards.

## Terminology


a. **Decision variables** are denoted by $x_1,x_2,\ldots,x_n$.

b. **Objetive function** mapping $\Re^n\rightarrow \Re$ in a linear way.

c. **Constraints** related to the $n$ decision variables. These constraints are typically expressed in the form of linear inequalities.

> The **optimization rule** consist in `maximizing (or minimizing)` the `objective function` with regards to the $n$ `decision variables` subject to the given constraints.

## Example: Motivating case study

Lets consider **two decision variables**, $x_1$ and $x_2$, and an **objetvice function** given by 
$$
f(x_1,x_2)=350 x_1 + 300 x_2.
$$
The **optimization rule** consists in *maximizing* $f(x_1,x_2)$ subjet to the following constraints:

\begin{eqnarray}
x_1 + x_2 & \leq & 200 \nonumber \\
9 x_1 + 6 x_2 & \leq & 1566 \nonumber \\
12 x_1 + 16 x_2 & \leq & 2880 \nonumber \\
x_1 & \geq & 0 \nonumber \\
x_2 & \geq & 0. \nonumber
\end{eqnarray}

## Remarks

Recall that in **linear programming**:

a. Both `objetive function` & `constraints` **must all be linear**

b. Typically, `objetive variables` are all possitive.

c. If `objective variables` are integers, then the problem turns into **Integer Programme (IP)**, which is far more challenging.


---

# Modelación y resolción de problemas simples

---

# Modelación de problemas combinatorios

---

# Lecturas de soporte

---

# Lecturas para la siguiente semana


