---
title: CD2007 Metodos Cuantitativos y de Optimizacion
subtitle: Teoria de Decision - Parte 2
author: Juan Carlos Martinez Ovando
institute: Escuela de Negocios
#titlegraphic: /Dropbox/teaching/clemson-academic.png
fontsize: 10pt
output:
 ioslides_presentation:
    smaller: true
#    logo: ~/Dropbox/teaching/clemson-paw-transparent.png
    css: ~/svm-r-sources/svm-ioslides-css.css    
 beamer_presentation:
    template: ~/svm-r-sources/svm-latex-beamer.tex
    keep_tex: true
# toc: true
    slide_level: 2
---

---

# 2. Elementos de la teoría de decisiones

## 2.6. Incertidumbre

Hemos visto que cada acción $a_j$ puede estar acompañada por una colección de $C_j$ consecuencias $\{c_{j1},\ldots,c_{jC_{j}}\}$.

La *regla de decisión promedio* nos brinda la oportunidad de tomar decisiones en $\mathcal{A}$ con base en el conjunto de consecuencias plausibles.

\textcolor{orange}{$\triangle$ Pero, no todas las consecuencias son igualmente plausibles.}

---

Para incorporar esta consideraciones, se permite la posibilidad de incorporar una **cuantificación de la incertidumbre** a través de una medida de probabilidad
$$
Q:\mathcal{C}_j \rightarrow (0,1),
$$
donde $Q(c_{ji})$ denota la probabilildad de la consecuencia $c_{ji}$ de manifestarse, una vez que la acción $a_j$ haya sido adoptada.

---

La cuantificación de la incertidumbre acerca de $\mathcal{C}$ puede ser realizada de dos formas:

a. Subjetiva

b. Objetiva

_No prestemos más atención a estas formas, de momento._

---

**\textcolor{orange}{Comentarios}**

* Tanto la funcion de preferencias, $U$, como la cuantificacion de incertidumbre, $Q$, son definidas previamente a tomar la decision y recolectar evidencia (datos) de decisiones homogeneas.

* Ambas funciones se definen *separadamente*.

---

## 2.7. Regla de decisión bajo incertidumbre

Con base en la incorporación de $Q$, tenemos ahora los elementos $(\mathcal{A},\mathcal{C},U,Q)$ que definen el marco de referencia conductual de decisiones bajo consecuencias múltiples con incertidumbre.

Asi, podemos incorporar la cuantificacion de $Q$ en la toma de decisiones, **conciliando** **preferencias** y **creencias/plausibilidad**.

---

### 2.7.1. Criterio de la utilidad mas probable

Con base en lo anterior, podemos adoptar una regla conductual en dos pasos:

1. Para cada acción $a_j$ se elige la consecuencia más probable, i.e.
$$
c_{j}^{*}=\arg\max_{c_{ji}\in\mathcal{C}_j}Q(c_{ji})
$$

2. Una vez definida la consecuencia mas probable para cada acción, la **regla de decisión** consistirá en elegir la acción máxima entre las más probables, i.e.
$$
a^{*}=\arg\max_{a_j \in \mathcal{A}} U(a_j,c_j^{*}).
$$

---

### 2.7.2. Criterio de la utilidad menos probable

En esta regla de decision, adoptamos una regla conductual en dos pasos:

1. Para cada acción $a_j$ se elige la consecuencia menos probable, i.e.
$$
c_{j}^{-}=\arg\max_{c_{ji}\in\mathcal{C}_j}Q(c_{ji})
$$

2. Una vez definida la consecuencia mas probable para cada acción, la **regla de decisión** consistirá en elegir la acción máxima entre las más probables, i.e.
$$
a^{-}=\arg\max_{a_j \in \mathcal{A}} U(a_j,c_j^{-}).
$$

---

### 2.7.3. Criterio de la utilidad esperada máxima

Con el propósito de incorporar tanto la _variabilidad_ como la _incertidumbre_ subyacente a $\mathcal{C}$, se define una regla conductual integrada en dos pasos:

1. Para cada acción $a_j$ se calcula la utilidad esperada, i.e.
$$
\mathbb{E}\left(U(a_j)\right)=\sum_{c_{ji}\in\mathcal{C}_j}Q(c_{ji})U(a_j,c_{ji})
$$

2. Una vez definida la utilidad esperada para cada acción, la **regla de decisión** consistirá en elegir la acción máximaentre las esperadas, i.e.
$$
a^{*}=\arg\max_{a_j \in \mathcal{A}} \mathbb{E}\left(U(a_j)\right).
$$

- ---------------------------------------------- -
  Esta es la regla de decisión que más se emplea 
  en la estadística 
- ---------------------------------------------- -

---

## 2.8. Comentarios

* La función de utilidad representa el deseo o preferencias individuales.

* Estas prefeencias son subjetivas, por lo que dada individuo en momentos particulares puede manifestar éstas de manera distinta.

* La medida de probabilidad, $Q$, es también subjetiva y dicta la plausibilidad de las consecuencias en cuestión.

* Ambas, $utilidad$ y $medida de probabilidad$ deben ser racionales u homogéneas a través de las acciones en $\mathcal{A}$

- ------------------------------------------------------------- -
  La regla de decisión general tendrá como propósito dictar 
  una conducta conciliada entre _plausibilidad_ y _preferencia_
- ------------------------------------------------------------- -

---

\textcolor{orange}{2.8. Comentarios... (Continuacion)}

En contextos inferenciales o administracion de riesgos, el problema de decision bajo incertidumbre es expresado en terminos de **perdida** en lugar de **utilidad**. 

Asi, pensemos que la percepcion de nuestras preferencias estara referida a perdidas como:
$$
L(a_j,c_{ji})=inv\left(U(a_j,c_{ji})\right),
$$
donde $inv(\cdot)$ se refiere a algun operador inverso.

\textcolor{blue}{$\triangle$ Con esta consideracion damos inicio al estudio de **riesgo**, definido como la perdida esperada }

