---
title: "Portfolio Allocation Problem"
author: "Juan Carlos Martinez-Ovando"
date: "17/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problema de asignacion de portafolios

## A. Espacio de Acciones

$\mathcal{A}={a_1,a_2}$

## B. Espacio de consecuencias

$\mathcal{C}=\{c_{11},c_{12},c_{21},c_{22}\}$

## C. Funcion de preferencias (Utilidad)

$\{U(a_i,c_{ij})\}_{i=1,j=1}^{2,2}$

## D. Regla de decision


1. `Optimista` - Elegir lo mejor de lo mejor, i.e. elegimos la accion que me genera la mejor consecuencia

2. `Pesimista` - Elegimos lo menos pero, i.e. dentro de los peores escenarios posible spara cada accion, elegimos la que sea menos mala

> Tanto A como B son `deficientes` en tanto que solo toman en cuenta extremos de consecuencias, pero no loas consecuencias intermedias.

3. `Agregada` - Elegir la accion que en promedio me brinda la mejor consecuencia posible.

Para cada accion, calculamos la consecuencia promedio

$\bar{U}(a_1)=(1/2) U(a_1,c_{11}) + (1/2)U(a_1,c_{12})$

y 

$\bar{U}(a_2)=(1/2) U(a_2,c_{21}) + (1/2)U(a_2,c_{22})$


donde 

$$
1/2 = \text{Posibilidad de tener la consecuencia} c_{ij} \text{respecto a la accion } a_i
$$

Consideramos ahora la extension, que consiste en sustuir la nocion de *posibilidad de consecuencias* por la nocion de *pobabilidad de consecuencias*

> i.e. las consecuencias en $\mathcal{C}$ se convierten en inciertas para nosotros, y por consecuencia, podemos aompañarlas con una función de porbabilidad.

## F. Espacio de incertidumbre

$\mathcal{I}=\mathcal{C},$

## G. Regla de probabilidad

Cuantificacion de las probabilidades de que cada una de las consecuencias se manifiesten o no,

i.e.

Para cada accion, $a_i$, definira una funcion
$$
\mathbb{P}(c_{ij})=\text{Probabilidad de que al haber seleccionado la accion } a_i \text{se haya manifestado la consecuencia }c_{ij}. 
$$

De lo anterior se siguie que para laccion $a_1$, tenemos el pra de probabilidades
$\mathbb{P}(c_{11})$ y $\mathbb{P}(c_{12})$, ambas positivas, de manera que 
$$
\mathbb{P}(c_{11}) + \mathbb{P}(c_{12}) = 1.
$$

De esta forma, en la regla agregada de decision, podriamos remplzar los coeficientes (1/2), por sus correspondientes probabilidaes, i.e.

$\mathbb{P}(c_{11}) U(a_1,c_{11}) + \mathbb{P}(c_{12}) U(a_1,c_{12})=\mathbb{E}(U(a_1))$.

De manera analoga, tendriamos

$\mathbb{P}(c_{21}) U(a_1,c_{11}) + \mathbb{P}(c_{22}) U(a_1,c_{12})=\mathbb{E}(U(a_2))$.


> La regla de decision se definira como la eleccion de la accion que el terminos esperados me arroje la mayor utilidad posible.


## Resumiendo

Los componentes el problema de decision bajo incertidumbre son:

a. Espacio de acciones/decisiones (tengo control)

b. Espacio de incetidumbre (no tengo control)

c. Combinacion de (a) y (b), serian las consecuencias

d. Cuantificacion de preferencias (utilidades)

e. Funcion de probabilidad (cuantificar posibilidades)

f. Relga de decision / **El unico enfoque admisible, sera el de la regla de decision agregada en esperanza**

$$
a^* = \arg\max_{a\in\mathcal{A}} \mathbb{E}_{\mathbb{P}_a}(U(a,c_a)). 
$$

----


Retomando...

a. Espacio de acciones

La combinacion de diferentes porciones de inversion de un monto generico $M$ distribuidas entre los cuatro tipos de activos financieros.

> Este es un componente composicional, i.e. $M_1$ monto de inversion en el activo 1, $M_2$ monto de inversion en el activo 2, ..., $M_4$ monto de inversion en el actuivo $, tendriamos $$M_1+M_2+M_3+M_4 = M.$$

Estandarizando la ultima relacion con respecto a $M$, tendriamos lo siguiente
$$w_1+w_2+w_3+w_4 = 1,$$

donde $w_i = M_i/M$.

De esta forma, el espacio de acciones quedaria definido como
$$
\mathcal{A}=\{(w_1,w_2,w_3,w_4): w_i \geq 0 \text{ y } w_1+w_2+w_3+w_4=1\}.
$$

Se conoce como el simplejo de dimension 3.

Casos particulares en $\mathcal{A}$

* Un caso $(0,1/2,1/4,1/4)$

* Otro caso $(1/4,1/4,1/4,1/4)$.

## B. Incertidumbre

Variacion de precios de los activos como la medida de rentabilidad de la inversion

* $P_{1t}$ -  Precio del activo 1 en el tiempo $t$

* $P_{2t}$ -  Precio del activo 2 en el tiempo $t$

* $P_{3t}$ -  Precio del activo 3 en el tiempo $t$

* $P_{4t}$ -  Precio del activo 4 en el tiempo $t$.

La rentabilidad la veremos como la variacion de precios entre dos momento de tiempo, $t$ y $(t+1)$ que definene el horizonte de inversion, nos indicara si ganamos o perdemos en la inversion y en que cantidad.

> La decision que tomaremos la realizamos en el tiempo $t$, el resultado de la inversion lo veremos en el tiempo $(t+1)$, solo que al tiempo $t$ no es deconocido que pasara al final de $(t+1)$.

La rentabilidad la mediremos de dos formas

### Retorno ordinario

$$
R_{1t}=100 * \left(\frac{P_{1,t+1}-P_{1,t}}{P_{1,t}}\right).
$$

### Retorno logaritmico***

$$
r_{1t}=100 * \left(\log P_{1,t+1}- \log P_{1,t}\right).
$$


Lo que es incierto para mi en el tiempo $t$, es el resultado que tendra cada una de las inversiones.

* Ganar , $r_{1,t}>0$

* Neutro , $r_{1,t}=0$

* Perder , $r_{1,t}<0$.

Lo complementaremos con sus correspondientes probabilidades

$$q_{1,g}=\mathbb{P}(r_{1,t}>0)$$

$$q_{1,n}=\mathbb{P}(r_{1,t}=0)$$

$$q_{1,p}=\mathbb{P}(r_{1,t}<0)$$

Es decir, el espacio de incertidumbre, sera la combinacion de posibles resultados de los cuatro activos financieros

$$\mathbb{I}_1=\{g, n, p\}$$

$$\mathbb{I}_2=\{g, n, p\}$$
$$\mathbb{I}_3=\{g, n, p\}$$

$$\mathbb{I}_4=\{g, n, p\}$$

De tal formqa que en conjunto, la combinacion de los cuatro posibles resultados definira el espacio de incertidumbres

$$
\mathcal{C}=\{ (g,g,g,g), (g,g,g,n), (g,g,g,p), 
               (g,g,n,p), (g,g,p,p), ... 
               \}
$$

Asi seriasn $3^4=81$ conbinaciones de posibles resultados en $\mathcal{I}$.

Consideren que para el `activo 1` las siguientes probabilidades

$q_{1,g}=1/3$, $q_{1,n}=1/3$, $q_{1,p}=1/3$

Para el activo 2, consideren

$q_{2,g}=1/9$, $q_{2,n}=3/9$, $q_{2,p}=5/9$

Para el activo 3, consideren

$q_{3,g}=7/9$, $q_{3,n}=0/9$, $q_{3,p}=2/9$

Para el activo 4, consideren

$q_{4,g}=2/9$, $q_{4,n}=0/9$, $q_{4,p}=7/9$.


Con base en esas probabilidades, y bajo el supuesto que los activos ganan o pierden entre si de manera independiente, calculen todas las probabilidades de los 81 posibles resultados que involucran el espacio de incertidumbre $\mathcal{I}$ de este problema.

$$
\mathbb{P}(g,g,g,g)=\mathbb{P}_1(g) \times \mathbb{P}_2(g) \times \mathbb{P}_3(g) \times \mathbb{P}_4(g) = q_{1,g} \times q_{2,g} \times q_{3,g} \times q_{4,g}
=1/3 \times 1/9 \times 7/9 \times 2/9.
$$
Lo mismo, de manera analoga para las demas 80 posibilidades en $\mathcal{I}$.