---
title: "CD2007 Semana 02 Solución Caso2 Parte 2"
author: "Juan Carlos"
date: "28/2/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Case 2

## Part 2: Solution

In **extension** to the previous solution (`Part 1`), we need to introduce four additional binary variables,
$$
b_1 = 
\begin{cases}
1, & \text{ if there is production in month } i,\\
0, & \text{ otherwise}.
\end{cases}
$$

We define the `decision variables` (label and order) as follows:
$$
(q_1,q_2,q_3,q_4,s_1,s_2,s_3,s_4,b_1,b_2,b_3,b_4).
$$

Accordinly, the specification of the `lpSolve` inputs and solution of the `LP` problem are given by:

```{r}
I.rule <- "min"
II.fobj <- c(12,12,12,12,2,2,2,2,1000,1000,1000,1000)
III.Acon <- matrix(c(1,0,0,0,-1,0,0,0,0,0,0,0,
                     0,1,0,0,1,-1,0,0,0,0,0,0,
                     0,0,1,0,0,1,-1,0,0,0,0,0,
                     0,0,0,1,0,0,1,-1,0,0,0,0,
                     -1,0,0,0,0,0,0,0,400,0,0,0,
                     0,-1,0,0,0,0,0,0,0,400,0,0,
                     0,0,-1,0,0,0,0,0,0,0,300,0,
                     0,0,0,-1,0,0,0,0,0,0,0,300), 
                   nrow = 8, 
                   byrow = TRUE)
IV.dir <- c("=","=","=","=",">=",">=",">=",">=")
V.bound <- c(100,200,150,400,0,0,0,0)

library("lpSolve")
case2p2.sol <- lp(I.rule,
                II.fobj,
                III.Acon,
                IV.dir,
                V.bound)

case2p2.sol$objval

case2p2.sol$solution
```
