---
title: CD2007 Metodos Cuantitativos y de Optimizacion
subtitle: Teoria de Decision - Proyecto
author: Juan Carlos Martinez Ovando
institute: Escuela de Negocios
#titlegraphic: /Dropbox/teaching/clemson-academic.png
fontsize: 10pt
output:
 ioslides_presentation:
    smaller: true
#    logo: ~/Dropbox/teaching/clemson-paw-transparent.png
    css: ~/svm-r-sources/svm-ioslides-css.css    
 beamer_presentation:
    template: ~/svm-r-sources/svm-latex-beamer.tex
    keep_tex: true
# toc: true
    slide_level: 2
---


Background
---

* In the late 50s Markowitz laid down the foundations of the modern asset allocation.

* The main idea of `diversification`, which is at its heart, is still deeply rooted in investor's mindset
dictating allocation strategies.

* Rationale:

> ...do not put all the eggs in the same basket...

* It gave a quantitative dimension of concepts like `risk` and `return` and their mutual dependence and `trade-off`

Stylezed facts about returns
---

* In first place, especially for daily data, it widely known they are not well described by `normal distributions`, as it is sometimes assumed.

* Second, `volatility` exhibits `clustering behaviour` (i.e. periods of high and low volatility seem to alternate in contrast with the `homoscedastic` assumptions of Markowitz).

* Third, `correlations` are assumed constant in the model while an overwhelming evidence has been given, that they are prone to increase during turbulent times.

Outline of the problem
---

a. We will consider the problem of how to choose, given a fixed investment amount (the budget constraint), the optimal composition of a top portfolio (i.e., the weights, $w$, to be given to several sub-portfolios).

b. We assume that each sub-portfolio is invested in a `different asset class` and that it can be associated with a single dominant `risk factor`.

Dataset
---

The `dataset` we will use consists of four asset classes: 

1. `Government Bonds`, 

2. `Investment-Grade Credit Bonds`, 

3. `Equities`, 

4. `High-Grade RMBS Securities` (called asset class Bond, Credit, Equity and Mortgage, respectively, in the following).

Financial indices
---

Thus, the following indices are used:

a. For `Government Bond` the `BarCap US Treasury Index`

b. For `Investment-Grade Credit Bonds` the `BarCap US Credit Index`

c. For `Equity` the `S&P 500`

d. For `High-Grade RMDS Securities` the `BarCap US MBS Index`

> The dataset shall consists of daily returns for the above four indices, covering the period `February 1997` to `June 2019`