---
title: "Ejercicios de teoría de decisión"
author: "Juan Carlos Martinez-Ovando"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejercicio 1

El propietario de la tienda de ropa `Los Trapos`, ante el inminente
arribo del otoño, debe decidir cuántos suéteres ha de adquirir de sus proveedores.Puede solicitar el material en múltiplos de 100 unidades. Si ordena 100 suéteres, estos tienen un costo unitario de 150 pesos, si ordena 200 el costo unitario es de 120 pesos y si ordena 300 suéteres o más, el costo unitario es de 90 pesos.

En cualquier caso, `Los Trapos` vende suéteres, en temporada otoño-invierno, a un precio de 180 pesos y si sobran algunos los remata, después de la temporada, a la tercera parte del precio. Además, el propietario del almacén considera que cada suéter que le sea solicitado en temporada y que no pueda vender (por falta de existencias) le supone una pérdida equivalente a 15 pesos, en términos económicos.

Si por facilidad, el propietario supone que la demanda de suéteres en temporada será de 100; 150; 200; 250 ó 300 unidades con probabilidades $$1/6; \ 2/9; \ 1/3; \ 2/9; \ 1/18,$$
respectivamente y que la utilidad que le reporte cada consecuencia se mide exclusivamente en términos monetarios, entonces

* Describe la estructura del problema de decisión.

* Identifica las decisiones inadmisibles en este problema. ¿Le parece razonable la eliminación de estas decisiones? >Por qué?

* Resuelve el problema empleando el enfoque optimista.

* Resuelve el problema vía el enfoque agregado.

* Resuelve el problema vía el enfoque de utilidad esperada.

# Ejercicio 2

El día de cumpleaños número 20, un paciente es admitido
en el hospital con síntomas que sugieren la enfermedad `A` (con probabilidad $0.4$) o bien la enfermedad `B` (con probabilidad $0.6$).

Cualquiera que sea la enfermedad que en realidad padece, si no se trata médicamente morirá ese mismo día (con probabilidad $0.8$) o bien, sobrevivirá sin consecuencias para su salud (con probabilidad $0.2$). El médico que recibe a este paciente tienen tres opciones:

a. No administrar tratamiento alguno.

b. Tratar al paciente con el fármaco `F`.

c. Realizar cirujía al paciente.

Tanto la cirujía como la administración del fármaco involucran riesgos.

Sin importar la enfermedad, el paciente puede morir durante la operación (con probabilidad $0.5$). De la misma manera, sin importar la enfermedad, el fármaco puede ocasionar una reacción alérgica mortal (con probabilidad $0.2$).

Si el paciente sobrevive a los efectos adversos del fármaco, y tenía la enfermedad `A`, entonces le puede curar con una probabilidad de $0.9$, o puede que no tenga efecto alguno. Si el paciente tenía la enfermedad `B`, con seguridad el fármaco no tendrá un efecto curativo.

Por otra parte, si el paciente sobrevive a la cirujía, esta lo curará (con una probabilidad de $0.5$) si padecía la enfermedad `A`, en caso contrario no tiene efecto.

Por otro lado, si pacede la enfermedad `B`, la cirujía lo curará (con probabilidad $0.6$) y no tendrá efecto con probabilidad $0.4$.

En cualquier caso, si se recupera, el paciente tiene una esperanza de vida de 50 años más a partir de la fecha de consulta.

La **pregunta** consiste en ¿qué tratamiento es más conveniente? 