---
title: CD2007 Metodos Cuantitativos y de Optimizacion
subtitle: Teoria de Decision - Parte 1
author: Juan Carlos Martinez Ovando
institute: Escuela de Negocios
#titlegraphic: /Dropbox/teaching/clemson-academic.png
fontsize: 10pt
output:
 ioslides_presentation:
    smaller: true
#    logo: ~/Dropbox/teaching/clemson-paw-transparent.png
    css: ~/svm-r-sources/svm-ioslides-css.css    
 beamer_presentation:
    template: ~/svm-r-sources/svm-latex-beamer.tex
    keep_tex: true
# toc: true
    slide_level: 2
---


---

# 1. Teoria de la Decision

## 1.1. Objetivos

El objetivo de la teoría de decisión es el de brindar un marco conductual que nos ayude a distinguir los elementos los cuales los individuos tomamos decisiones cotidianas.

Con este marco, podremos **responder preguntas inferenciales** con esta formalidad.

---

# 2. Elementos de la teoría de decisiones

## 2.1. Acciones

El elemento $(a)$ del problema de decisiones será referido al **espacio de acciones**, espacio donde descansan las alternativas que tenemos como individuos. 

Denotamos a este espacio como,
$$
\mathcal{A}=\{a_1,\ldots,a_A\},
$$
siendo $A$ el número de acciones disponibles (notemos que puede ser infinito, inclusive).

_Notemos que cada acción que consideremos estará acompañada por lo que le sigue, una o varias consecuencias._

---

## 2.2. Consecuencias

El elemento (b) del problema corresponde al **espacio de censecuencias**, el cual estará referido/anclado a las acciones disponibles en $\mathcal{A}$. 

En un contexto general, cada acción $a_j$ estará acompañada por la colección de consecuencias posibles, denotado por
$$
\mathcal{C}_j=\{c_{j1},\ldots,c_{jC_{j}}\},
$$
siendo $C_{j}$ el número de posibles consecuencias asociadas con la acción $a_j$.

El espacio de todas las consecuencias posibles es denotado por
$$
\mathcal{C}=\times_{j=1}^{A}\mathcal{C}_j.
$$

---

**\textcolor{orange}{Diagrama}**

---

Caso particular, **sin incertidumbre**, i.e. _una consecuencia por acción_.

* Para cada acción $a_j$ existe sólo una consecuencia, i.e.
$$
a_j \rightarrow c_{j1},
$$
para $j=1,\ldots,A$.

_\textcolor{orange}{Al interior del espacio de consecuencias definiremos como individuos reglas de preferencias.}_

---

## 2.3. Preferencias

**Se supondrá que las preferencias que podamos definir entorno a $\mathcal{}$ serán racionales (i.e. homogéneas a las acciones).**

Las preferencias están definidas como un operador binario "$\succ$" bajo el cual para cada par de consecuencias, $c_{jk}$ y $c_{jl}$ diremos que 

--------------------------------- ------- ----------------------------------
$c_{jk}$ es preferible a $c_{jl}$  $\iff$  $c_{jk}\succ c_{jl}$
--------------------------------- ------- ----------------------------------

---

De la relación anterior tendremos una de las siguientes tres opciones para $c_{jk}$ y $c_{jl}$:

1. $c_{jk}$ es preferible a $c_{jl}$  $\iff$  $c_{jk}\succ c_{jl}$

2. $c_{jl}$ es preferible a $c_{jk}$  $\iff$  $c_{jl}\succ c_{jk}$

3. $c_{jk}$ y $c_{jl}$ son indiferentes  $\iff$  $c_{jk}\succ c_{jl}$ y $c_{jl}\succ c_{jk}$

\textcolor{orange}{$\triangle$ Notemos que la regla de preferencia $\succ$ es un operador cualitativo.}

---

### 2.3.1. Acciones y consecuencias

La regla de preferencia $\succ$ está definida no solo en $\mathcal{C}$ (o cada $\mathcal{C}_{j}$ para $j=1,\ldots,A$), sino que define una regla de preferencias en las acciones $\mathcal{A}$ indirectamente.

Para entender esto, consideremos el **caso sin incertidumbre** donde cada acción tiene acompañana una consecuencia, i.e.

$$
\mathcal{A}\times\mathcal{C}=\{(a_j,c_{j1})\}_{j=1}^{A}.
$$

Diremos, $(a_{j},c_{j1})$ es preferible a $(a_{k},c_{k1})$  $\iff$  $c_{j1}\succ c_{k1}$.


Es decir,

--------------------------------- ------- ----------------------------------
$a_{j}$ es preferible a $a_{k}$   $\iff$  $c_{j1}\succ c_{k1}$
--------------------------------- ------- ----------------------------------

\textcolor{orange}{$\triangle$ Recordemos que $\succ$ es un operador cualitativo.}

---

## 2.4. Función de utilidad

Con el propósito se estandarizar y hacer comparables las preferencias individuales (comparables entre acciones y entre individuos), definimos el elemento $(d)$ el problema de decision, referido a la **función de utilidad**.

La función de utilidad se defines como la función 
$$
U:\mathcal{A}\times\mathcal{C} \rightarrow \Re,
$$
inducida por el operador $\succ$.

\textcolor{orange}{$\triangle$ Ahora, nuestras preferencias son manifestadas cuantitativamente, de manera que }

--------------------------------- ------- ----------------------------------
$a_{j}$ es preferible a $a_{k}$   $\iff$  $U(a_j,c_{j1}) > U(a_k,c_{k1})$
--------------------------------- ------- ----------------------------------

(En el contexto de _decisión sin incertidumbre_).

---

## 2.5. Regla de decision

Con base en la triada $(\mathcal{A},\mathcal{C},U)$ definimos ahora la _regla conductual_ o _regla de decisión_.

### 2.5.1. Contexto sin incertidumbre

En el _contexto sin incertidumbre_, $\{(a_j,c_{j1})\}_{j=1}^{A}$ elegiremos la acción óptima $a^{*}$ definida como
\begin{eqnarray}
a^{*}=\arg\max_{a_j\in\mathcal{A}} U(a_j,c_{j1}).
\end{eqnarray}

- ------------------------------------------ -
  Esta es la acción que domina $\mathcal{A}$
- ------------------------------------------ -

---

### 2.5.2. Contexto de consecuencia múltiples

En un contexto general, cada acción estará seguida por más de una consecuencia. 

En este caso, la regla de decisión puede definirse de varias formas. Consideraremos tres: 

1. Optimista (lo mejor de lo mejor)

2. Pesimista (lo menos malo)

3. Agregado

---

#### 2.5.2.1. Optimista

Se define en dos pasos:

1. Dentro de cada acción $a_j$ elegimos a consecuencia más deseable, $c_j^{*}$, donde 
$$
c_j^* = \arg\max_{C_{ji}\in\mathcal{C}_j} U(a_j,c_{ji}).
$$
2. Se elige la opción $a^{*}$ que maximiza la _mejor consecuencia_, i.e.
$$
a^{*}=\arg\max_{a_j\in\mathcal{A}}U(a_j,c_{j}^{*}).
$$

- ------------------------------------- -
  Este $a^{*}$ es lo mejor de lo mejor 
- ------------------------------------- -

---

#### 2.5.2.2. Pesimista

Se define en dos pasos:

1. Dentro de cada acción $a_j$ elegimos a consecuencia menos deseable, $c_j^{-}$, donde 
$$
c_j^{-} = \arg\min_{C_{ji}\in\mathcal{C}_j} U(a_j,c_{ji}).
$$
2. Se elige la opción $a^{*}$ que maximiza la _mejor consecuencia_ menos deseable, i.e.
$$
a^{-}=\arg\max_{a_j\in\mathcal{A}}U(a_j,c_{j}^{-}).
$$

- ----------------------------- -
  Este $a^{-}$ es lo menos peor 
- ----------------------------- -

---

#### 2.5.2.3. Promedio

Se define en dos pasos:

1. Dentro de cada acción $a_j$ cuantificamos la utilidad promedio entre las posibles consecuencias,  
$$
\bar{U}(a_j) = \frac{1}{C_j}\sum_{j=1}^{C_j}U(a_j,c_{ji}).
$$
2. Se elige la opción $a^{*}$ que maximiza la _mejor consecuencia_ menos deseable, i.e.
$$
a^{*}=\arg\max_{a_j\in\mathcal{A}}\bar{U}(a_j).
$$

- --------------------------------- -
  Este $a^{*}$ es lo mejor promedio 
- --------------------------------- -
